// website/src/components/navbar/main.svelte
<script>
import {
    goto
} from "$app/navigation";

import {
    hide,
    showPopout
} from "../../stores/navbar";
import {
    navbarmain,
    navbarmenu
} from "../../scripts/classes";
import {
    home
} from "../../stores/layout";

let topbarclass = navbarmain
let navbarmenuclass = navbarmenu
let homehref = '/'
let popoutshown = false

hide.subscribe((x) => {
    topbarclass = `${navbarmain} ${x && !popoutshown ? '-translate-y-full' : ''}`
})

showPopout.subscribe((x) => {
    popoutshown = x
    navbarmenuclass = `${navbarmenu} ${x ? 'ri-close-line' : 'ri-menu-line'}`
})

home.subscribe(x => {
    homehref = x
})

const gohome = () => {
    if (location.pathname === homehref) return

    goto(homehref)
}

const menuclicked = () => {
    showPopout.update(x => !x)
}
</script>

<nav class={topbarclass}>
    <div class="flex w-screen h-full items-center px-1">
        <img src="/logo-long.svg" alt="long version of logo" class="h-8 px-2 hidden sm:block" on:click={gohome}>
        <img src="/logo-short-white.svg" alt="short version of logo" class="h-6 px-2 sm:hidden" on:click={gohome}>

        <span class="flex-1"></span>

        <span class={navbarmenuclass} on:click={menuclicked}></span>
    </div>
</nav>

// www/components/navbar/main.vue
<template>
  <div
    id="nav"
    ref="navbar"
    class="w-screen top-0 h-14 fixed border-b bg-gray-100 border-gray-300"
  >
    <div class="flex w-full h-full items-center px-1">
      <img
        src="/img/logo-long.svg"
        alt="long version of logo"
        class="h-8 px-3 hidden sm:block"
        @click="gohome"
      />
      <img
        src="/img/logo-short.svg"
        alt="short version of logo"
        class="h-6 px-3 sm:hidden"
        @click="gohome"
      />

      <span class="flex-1"></span>

      <span :class="navbarmenuclass" @click="menuclicked"></span>

      <NavbarDesktop />
    </div>
  </div>
</template>

<script>
export default {
  props: {
    homepage: {
      type: String,
      default: () => '/',
    },
  },
  computed: {
    navbarmenuclass() {
      return `${
        useNavbar.mobilenav ? 'ri-close-line' : 'ri-menu-line'
      } px-2 py-1 sm:hidden text-secondary navbarmenu`;
    },
    hide() {
      return useNavbar.hide;
    },
  },
  watch: {
    hide(val) {
      const navbarHeight = this.$refs.navbar.offsetHeight;

      useAnime({
        targets: this.$refs.navbar,
        top: val ? -navbarHeight : 0,
        duration: 250,
        easing: 'cubicBezier(0.4, 0, 0.2, 1)',
      });
    },
  },
  mounted() {
    const resizenavbar = () => {
      this.$refs.navbar.style.width =
        document.documentElement.clientWidth + 'px';
    };
    window.addEventListener('resize', resizenavbar);

    resizenavbar();
  },
  methods: {
    menuclicked() {
      useNavbar.mobilenav = !useNavbar.mobilenav;
    },
    gohome() {
      if (this.$route.path === this.homepage) return;

      console.log(this.$route.path);
      this.$router.push(this.homepage);
    },
  },
};
</script>

<style>
@keyframes color {
  0% {
    color: #f79226;
  }
  50% {
    color: #ee2d30;
  }
  100% {
    color: #f79226;
  }
}

.navbarmenu::before {
  animation: color 9s infinite linear;
}
</style>
