// index/components/layout.vue
<template>
  <div class="w-screen h-screen overflow-hidden">
    <NavbarMain :homepage="homepage" />

    <div :class="toppadding + ' w-screen transition-all'"></div>

    <main
      ref="main"
      class="w-screen h-screen overflow-x-hidden dark:text-gray-100"
    >
      <slot class="overflow-y-auto" keep-alive />
      {{ homepage }}
    </main>

    <span :class="scrolltotopclass" @click="scrolltotop">
      <i class="ri-arrow-up-line text-gray-100"></i>
    </span>

    <PopoutMobile />
  </div>
</template>

<script>
import thememode from '../scripts/thememode'

const scrolltotopclass =
  'absolute bottom-0 right-0 m-2 px-2 py-1 rounded-lg transition duration-200'

export default {
  props: {
    homepage: {
      type: String,
      default: () => '/',
    },
  },
  data() {
    return {
      scrolltotopclass:
        scrolltotopclass + ' opacity-0 bg-primary pointer-events-none',
      hidescrollnum: 0,
      lastscrolledy: 0,
      toppadding: 'h-14 sm:h-20 w-screen',
    }
  },
  mounted() {
    thememode()

    this.$refs.main.addEventListener('scroll', this.scrollEvent)

    if (location.hash && document.querySelector(location.hash)) {
      document.querySelector(location.hash).scrollIntoView({
        behavior: 'smooth',
      })
    }
  },
  beforeDestroy() {
    this.$refs.main.removeEventListener('scroll', this.scrollEvent)
  },
  methods: {
    scrolltotop() {
      this.$refs.main.scrollTo(0, 0)
    },
    scrollEvent({ target }) {
      const newscrollnum = Math.random()
      this.hidescrollnum = newscrollnum

      this.$store.commit('content/scrollTop', target.scrollTop)

      setTimeout(() => {
        if (newscrollnum !== this.hidescrollnum || target.scrollTop < 80) return
        this.scrolltotopclass = `${scrolltotopclass} bg-primary/10`
      }, 2000)

      this.scrolltotopclass = `${scrolltotopclass} ${
        target.scrollTop >= 80 ? 'bg-primary' : 'opacity-0 pointer-events-none'
      }`

      if (target.scrollTop - this.lastscrolledy <= 0 || target.scrollTop < 1) {
        this.$store.commit('topbar/setHide', false)

        this.toppadding = 'h-14 sm:h-20'
      } else {
        this.$store.commit('topbar/setHide', true)

        this.toppadding = 'h-0'
      }

      this.lastscrolledy = target.scrollTop
    },
  },
}
</script>

// site/pages/_layout.svelte
<script>
import {
    onMount
} from 'svelte';

import {
    hide,
    showPopout
} from "../stores/navbar";
import {
    layoutdiv,
    layoutscrolltotop
} from "../scripts/classes";

import hidenbfunc from "../scripts/hidenbfunc"

import "../css/app.css";
import thememode from "../scripts/thememode";
import NavbarMain from "../components/navbar/main.svelte"
import Popout from "../components/popout/mobile.svelte"

let divclass = layoutdiv
let scrolltotopclass = layoutscrolltotop + ' opacity-0 pointer-events-none';
let hidescrollnum = 0
let popoutshown = false

thememode();

onMount(() => {
    if (!location.hash) return;
    if (!document.querySelector(location.hash)) return;

    document.querySelector(location.hash).scrollIntoView({
        behavior: 'smooth'
    });
});

function mainscrolled(e) {
    const newscrollnum = Math.random()
    hidescrollnum = newscrollnum

    setTimeout(() => {
        if (newscrollnum !== hidescrollnum || e.target.scrollTop < 80) return
        scrolltotopclass = `${layoutscrolltotop} bg-primary/10`
    }, 2000)

    scrolltotopclass = `${layoutscrolltotop}${e.target.scrollTop < 80 ? ' opacity-0 bg-primary pointer-events-none' : ' bg-primary '}`
    hidenbfunc(e)
}

function scrolltotop() {
    document.querySelector('main').scrollTo(0, 0)
}

showPopout.subscribe((x) => {
    popoutshown = x
})

hide.subscribe((isHide) => {
    divclass = `${layoutdiv}${!isHide && !popoutshown ? ' pt-14 sm:pt-20' : ''}`
})
</script>

<NavbarMain />

<div class={divclass}>
    <main class="overflow-x-hidden overflow-y-auto h-full w-screen" on:scroll={mainscrolled}>
        <slot />
    </main>
</div>

<span class={scrolltotopclass} on:click={scrolltotop}>
    <i class="ri-arrow-up-line text-gray-100"></i>
</span>

<Popout></Popout>
